### ISSUE TITLE
Sorting option by datetime added to database

### ISSUE THREAD

**Issue by AaronSofaer** [ResistanceCalendar/resistance-calendar-api#102]
Ragtag's CTA Aggregator would love to incorporate data from the Resistance Calendar into the events side of our Calls to Action aggregation system. In order to do that without scraping the entire database every time we pull in new data, it would be nice to have an option to sort, in a paginated manner, by when something was added to RC's database; that way, we could say "Well, our last one was on page n, we'll get pages n and further" instead of pulling the full contents of RC.

**Comment by aaghevli** [comment]
The sorting and filtering is already supported by ODATA, but the actual fields were constantly being overridden by the ETL process to be the latest fields.

Created #103 to fix that. 

I also added a section in the README for that.

### Created / updated at queries

For ETL based processes, limiting the number of events queried for can be done by created_date and modified)date fields

* [https://resistance-calendar.herokuapp.com/v1/events?$filter=created_date gt '2017-03-01'](https://resistance-calendar.herokuapp.com/v1/events?$filter=created_date%20gt%20'2017-03-01')
* [https://resistance-calendar.herokuapp.com/v1/events?$filter=created_date gt '2017-03-01'&orderby=created_date](https://resistance-calendar.herokuapp.com/v1/events?$filter=created_date%20gt%20'2017-03-01'&orderby=created_date)

**Comment by aaghevli** [comment]
Merged and deployed, thanks!
