### ISSUE TITLE
What's happening with events?

### ISSUE THREAD

**Issue by hypeJunction** [ResistanceCalendar/resistance-calendar-api#105]
We are noticing a super high volume of new events pouring in. Looking at the export it seems like created dates were reset, or you have somehow pulled in a ton of old events.

https://resistance-calendar.herokuapp.com/v1/events?page=0&per_page=100&%24filter=created_date%20gt%20%272017-10-13%27&order_by=created_date

It says there are 18k+ events added today.

**Comment by aaghevli** [comment]
hey @hypeJunction, sorry for that. I missed this message and so was not able to diagnose. Are you still experiencing issues?

**Comment by hypeJunction** [comment]
It seems fine now
