### ISSUE TITLE
Need /api API Entry Point resource

### ISSUE THREAD

**Issue by watzkej** [ResistanceCalendar/resistance-calendar-api#4]
Per OSDI spec, we need to have an /api endpoint that is the entry to our API.  Doing a get on /api will give back information about our API such as paging settings, OSDI version, and a link to each OSDI resource that we provide.  Take a look here for more info on OSDI AEP: https://opensupporter.github.io/osdi-docs/aep.html

**Comment by aaghevli** [comment]
See  #58 for details
