### ISSUE TITLE
Add Duplicate Validation

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-api#43]
There appear to be some duplicates in the API, as mentioned here:

https://github.com/ResistanceCalendar/resistance-calendar-map/issues/3

**Comment by aaghevli** [comment]
I think #50 may actually address this issue. I am going to merge this since I just cleared the database now in order to verify that it works. Updates were definitely broken, which may have manifested in some strange ways.

**Comment by aaghevli** [comment]
While not entirely in the spirit of this issue, which was to add validation, i'm closing this since #50 has seemed to fix the duplication issue. 

Once we get multiple events from multiple sources into this calendar, I think de-duplication may rear its ugly head again, but we seem okay for now.
