### ISSUE TITLE
Support images in ETL

### ISSUE THREAD

**Issue by aaghevli** [ResistanceCalendar/resistance-calendar-api#44]

**Comment by aaghevli** [comment]
Hey client folks, (@pdw207, @dorono, @dentemple, @pfarnach, @ekp), if anyone has time and wants to develop image support onto the following staging instance, it would go a long way in validating this code. If it's a larger task, I can create an issue in your project to validate this.

See featured_image_url property of the nodes returned from here:
https://resistance-calendar-pr-51.herokuapp.com/v1/events

There seems to be all sorts of crazy image transformations that can be done via url:
http://cloudinary.com/documentation/image_transformation_reference

Thanks!

**Comment by aaghevli** [comment]
I actually tested this in dev mode and it looks great!

**Comment by dorono** [comment]
@aaghevli - Did you still need front end help with this?

**Comment by aaghevli** [comment]
@dorono, i tested this myself off master and it worked, but I don't see the staging instance reflect the new images:

https://resistance-calendar.herokuapp.com/v1/events
