### ISSUE TITLE
Support /v1/events/{:id}

### ISSUE THREAD

**Issue by aaghevli** [ResistanceCalendar/resistance-calendar-api#46]
This is standard in OSDI events. May need to figure out the canonical ID first.

**Comment by gmisura** [comment]
I assume this

https://opensupporter.github.io/osdi-docs/events.html#scenario-scenario-retrieving-an-individual-event-resource-get

Is what you're referring to?

So when we go to
https://resistance-calendar.herokuapp.com/v1/events
And pull an ID out, we should be able to add it to the end of the URL:

https://resistance-calendar.herokuapp.com/v1/events/58e9a51774ceb9d94e194b17

And that should return 1 event, but it is currently returning 404, not found.

**Comment by aaghevli** [comment]
Yes, that's right. Right now the clients are using the ODATA search and taking the first element to work around this.

Ideally we would return our 'native' id in identifiers like the following an suppress the '_id' we use in mongodb and incorrectly send back.

Ideal return identifier:
```
"identifiers": [
  "resistance_calendar:58e9a51774ceb9d94e194b17",
  "facebook:1234565"
],
```

Then I suppose the clients should extract the resistance_calendar calendar and use the remaining ID (58e9a51774ceb9d94e194b17).

**Comment by sdotson** [comment]
I just went rogue on this one and took a stab at it. Let me know what you think at PR #55 .

**Comment by aaghevli** [comment]
Awesome! Had one question about the change but looks good!

**Comment by aaghevli** [comment]
w00t! Thank you!
