### ISSUE TITLE
Need scheduled FB feed caching app

### ISSUE THREAD

**Issue by watzkej** [ResistanceCalendar/resistance-calendar-api#5]
Rather than having every hit to our /api/events resource make a call to the FB feed, we would like to store this data in a backend datastore.  Our app will then be able to query the DB instead of FB for any new requests.

Couple of pointers:
1) See if we can model the data structure in Redis.  Redis has support for location queries but it may be a bit weak if we want to do more complex queries.  If so, we might want to look at something else like MongoDB which would allow us to query individual fields in the OSDI events when filtering.
2) Setup this little caching app as a scheduled job in Heroku.  See the following link for details on using Heroku scheduler: https://devcenter.heroku.com/articles/scheduler.  This should run pretty quickly so I think it will work as a scheduled task rather than having to run a full worker node.

**Comment by aaghevli** [comment]
Done via #29
