### ISSUE TITLE
Update ETL to parse address strings

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-api#65]
Currently 28% of the events in the MongoDB have no location data. The vast majority of these problematic events have *seemingly good addresses* on their event pages. The problem is the addresses are in a single string on the event page. The is VERY GOOD NEWS! It means we can fix almost all of the events that currently have zero coordinates or location data by making the ETL a tiny bit smarter so it parses those address strings. Here is a sample list of events that currently have no location data in our DB but have seemingly useable addresses:

**Comment by InciteDemocracy** [comment]
`SAMPLE EVENTS WITH SEEMINGLY GOOD ADDRESSES

https://www.facebook.com/events/1618451341504312/
Lincoln High School, Gym – 1600 SW Salmon Street, Portland, OR 97205

https://www.facebook.com/events/277604746028035/
16th St and H St Sacramento CA

https://www.facebook.com/events/1235834679799694/
299 2nd St, San Francisco, CA 94105-3123, United States

https://www.facebook.com/events/1413432692008898
Wyoming State Capitol, Cheyenne, WY 82001, United States

https://www.facebook.com/events/226067891186187/
Dag Hammarskjold Plz, New York, NY 10017, United States

https://www.facebook.com/events/1064148460333285
332 Main St, Longmont, CO 80501-5527, United States

https://www.facebook.com/events/536245803236632
5604 Manor Rd, Austin, TX 78723-4731, United States

https://www.facebook.com/events/312021379215829/
294 Hernando St, Memphis, TN 38126-1906, United States

https://www.facebook.com/events/626714440858644/
Bryant Park 78 2nd Ave. S Lake Worth, FL

https://www.facebook.com/events/202032483599126/
Banning Park 1331 Eubank Ave Wilmington, CA 90744

https://www.facebook.com/events/765277446983996/
440 Lake Hills Ln, Kalispell, MT 59901-7427, United States

https://www.facebook.com/events/272224793218901/
E Washington St & N Potomac St, Hagerstown, MD 21740

https://www.facebook.com/events/1764268537236572/
11 S Union St, Montgomery, AL 36104, United States

https://www.facebook.com/events/1406030466129937/
1515 SW 10th, Topeka, KS 66604 / SNCO-Topeka Libr Hughes 205

https://www.facebook.com/events/762100463941517
2 E Airy St, Norristown, PA 19401-4803, United States

https://www.facebook.com/events/399087037141918/
228 Walnut St, Harrisburg, PA 17101-1710, United States

https://www.facebook.com/events/229430257464114/
Sunrise Park, Palm Springs, CA USA

https://www.facebook.com/events/1637365736571548/
Fairfax High School, 3501 Rebel Run, Fairfax, VA 22030

https://www.facebook.com/events/1706513152980946/
10730 E Bethany Drive #240, Aurora, CO 80014

https://www.facebook.com/events/1494456417254050/
Clark Park South 43rd Street & Baltimore Avenue Philadelphia PA 19104

SAMPLE EVENTS WITH ADDRESSES THAT MAY BE TRICKY TO GEOCODE

https://www.facebook.com/events/316037735477317/
Richmond Convention Center, 5th and Marshall Streets

https://www.facebook.com/events/1003611679773151/
Wards Rd., Lynchburg, VA

https://www.facebook.com/events/1472129639466581
Town Hall 101 Field Point Rd, Greenwich CT 06830

https://www.facebook.com/events/1093356854102713/
5:30pm March at Coleman Park, 7:00pm Celebration at SEIU (521 Central Ave)

https://www.facebook.com/events/296016607479414/
630 S. Saginaw St. Flint, Michigan (downtown Flint)

https://www.facebook.com/events/770915313074307
New York, NY`

**Comment by aaghevli** [comment]
Fixed!
