### ISSUE TITLE
Store timezones in UTC format

### ISSUE THREAD

**Issue by KamillaKhabibrakhmanova** [ResistanceCalendar/resistance-calendar-api#73]
In reference to this:

[https://github.com/ResistanceCalendar/resistance-calendar-frontend/issues/131](https://github.com/ResistanceCalendar/resistance-calendar-frontend/issues/131)

**Comment by aaghevli** [comment]
See #74 for fix. Mongo already stores data in UTC format, but the issue was I was not serializing the timezone properly so rending would not work.
