### ISSUE TITLE
Add URLS to API for canceled FB events

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-api#75]
Example:

https://www.facebook.com/events/1831665597105855/

https://resistance-calendar.herokuapp.com/v1/events?$filter=_id%20eq%20%2758e9a50d74ceb9d94e193e02%27 

(no `browser_url` property)

**Comment by aaghevli** [comment]
The status property now tracks this and can be queried accordingly
