### ISSUE TITLE
/events/event_id endpoint throws 500 error

### ISSUE THREAD

**Issue by sdotson** [ResistanceCalendar/resistance-calendar-api#86]
Example:
https://resistance-calendar.herokuapp.com/v1/events/58e9a50d74ceb9d94e193e02

Output:
`{
"statusCode": 500,
"error": "Internal Server Error",
"message": "An internal server error occurred"
}`

Server log (when run locally):
```
Debug: internal, implementation, error 
    TypeError: Uncaught error: input.toJSON is not a function
    at render (/Users/stuartdotson/Desktop/resistance-calendar-api/routes/handlers/event.js:88:23)
    at /Users/stuartdotson/Desktop/resistance-calendar-api/routes/handlers/event.js:69:22
    at /Users/stuartdotson/Desktop/resistance-calendar-api/node_modules/mongoose/lib/query.js:2745:18
    at newTickHandler (/Users/stuartdotson/Desktop/resistance-calendar-api/node_modules/mpromise/lib/promise.js:234:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
I think the issue is that `toJSON()` isn't defined anywhere and isn't a part of `Object.prototype`or `String.prototype`. 

Diving deeper, I see it happens on this line:
```
const event = input.toJSON();
```
Troubleshooting this further, I see that input is already JSON, so it's puzzling why that was even there. In any case, the proper method to call would be `JSON.parse` if `input` were a string.

I'll create a PR to address this.

**Comment by aaghevli** [comment]
Given that the individual detail page for the event works, how is it possible that this fails?

https://www.resistancecalendar.org/event/5938338474ceb9d94e195867

**Comment by sdotson** [comment]
I just took a look in dev tools. That event detail page is working because it's pinging the endpoint `https://resistance-calendar.herokuapp.com/v1/events?$filter=_id%20eq%20%275938338474ceb9d94e195867%27`. It's using `events?$filter` and not `events/event_id`.

If `events/event_id` isn't being used anywhere, this isn't an emergency by any means.

**Comment by aaghevli** [comment]
Hrm... the render function is actually used in the list events page. 

https://github.com/sdotson/resistance-calendar-api/blob/2593ccc1c24aff93e2b25f03ea915462edc46235/routes/handlers/event.js#L45

```
const renderedEvents = osdiEvents.map(render);
```

I'll try to test this Sunday by adding unit tests

**Comment by aaghevli** [comment]
Yup! Seemed to work. Very odd.
